version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/urlshortener
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
